language: node_js
node_js:
  - 4
  - 5

notifications:
  slack:
    - secure: "Zfx4IT4LadBGvxVM5+IZqJ9ld8v4vK1iJJyD67oM6eW7GMsPm683LdX3JrdexH/CjuVxLdCSVovXpXNUuTK9kboswgLQkNlxd1DGPXSxnWITu4jY7ySeK7/eLB7pORAqFNyIlGHL61X5bCRWDoBUtlEu8O8UH+avybKRrwFGf1Mhu9nhhRNuH+bfUMDc8XaeZAPL+TTMiXsyCbgXKX6Yb9KZ/B4MWpFvq/BmI63vML6aIRvnGhJm2Nv9QLZVJOBGH2PGjQn4OKHgKmBswP0vpbJDx88Zg8UrJz3W8Yai/n5sYTWiotjgvCT844mEXS2bGzjSBj54AgW7Y8WQBlUlmii/3LVKOY19SQQWPicUR2pQaYVtk1mGdci4xaePH8EyHYHNoo7Bvo4vYIbynO5Jirv4Qm0TzIPTmeWvhvR4FiolYH0GfyM6yk+27MSLeyMX86KF6aJYldEklzD1JiAPVRFWtnfX5le12ThxHdJDuD5Qp83dbP3UG3FXEeAtoVYXXUHuemABu9B+9wzvL9TixvM8Moqm2Q3e5i7QqQusrNiv9U1/KAEPlVXp6VyZ/wRk8PbFZdLPdflCSXyPEqGAQTNT/wF4aM2QnoPQHtyCpclCl2+J1akYA46vpqEjiijhqXo0W+3WjtpTMW0f6vdvmuTFYmQSqoLLafqtMbLQOzo="
